In [6]:
import numpy as np
from pytz.tzinfo import unpickler

print("Hi")

Hi


In [4]:
print("Hello World")

Hello World


In [5]:
print("Hi")

Hi


###### <div style="font-family:'Georgia', serif; text-align:center;">
  <h1 style="font-size:36px; margin-bottom:0;">
    <span style="font-size:48px;">S</span>ESSION - 2 <span style="font-size:28px;">[On Files , Classes , Operators and Inheritance]</span>
  </h1>
</div>

<div style="font-family:'Georgia', serif; font-size:18px; margin-top:10px; margin-left:50%;">
  – 27-02-2025 [Friday]
    <br>
    <br>
    <br>
</div>

transient Programs - Data Disappears once the program stops running


In [12]:
f = open("demo.txt")
#readline --- Read line by line
f.readline()

'This is the Frist Line,\n'

In [17]:
f = open("demo.txt")
for line in f :
    for wd in line.split():
        print(wd.strip(".,"))

This
is
the
Frist
Line
It
is
the
text
file
containing
three
lines
Hence
this
is
the
third
line


In [16]:
f = open("animals.txt" , "w")
f.write("Cat\n")
f.write("Dog\n")
f.write("Bird\n")

f.close()


In [19]:
f = open("animals.txt" , "r")
for line in f:
    print(line , end = "")

Cat
Dog
Bird


In [32]:
#Pickle Module

import pickle
'''pickle.dumps() ( short for dump string) creates a binary string representing an object '''

t1 = [1,"two" , 3.0]
s = pickle.dumps(t1)
print(s)
print()

'''The output is a raw binary string that encodes the list t1. Each sumbol encodes one byte. More detail later in the course '''

t2 = pickle.loads(s)
print(t1 == t2)
'''
- pickle.loads(s) takes the binary string s and recreates the original Python object (unpickles it).
- t2 is now a new list with the same contents as t1.
- t1 == t2 → True because both lists have the same elements.
'''
print()
print(t1 is t2)

'''
- is checks whether both variables point to the same object in memory.
- Even though t1 and t2 look identical, they are different objects created at different times.
- So t1 is t2 → False.
'''
print("")

b'\x80\x04\x95\x16\x00\x00\x00\x00\x00\x00\x00]\x94(K\x01\x8c\x03two\x94G@\x08\x00\x00\x00\x00\x00\x00e.'

True

False



In [40]:
import os

'''os.getcwd() returs a string corresponding to the current woring directory
os.listdir() lists the contents of its argument , or the current directory if no argument
os.chdir() changes the working directory After calling chdir() we're in different cwd
os.path.exists ---- checks whether or not file directory/exists
os.path.isdir ----  Check wheter or not this is a directory os.path.isfile() works diagonally
'''

cwd = os.getcwd()
print(cwd)

print(os.listdir())

C:\Users\A L SRI YADAV\Desktop\Academics\Sem 2\PL 2
['.idea', 'animals.txt', 'Class.ipynb', 'Class.py', 'demo.txt', 'main.py']


###### <div style="font-family:'Georgia', serif; text-align:center;">
  <h1 style="font-size:36px; margin-bottom:0;">
    <span style="font-size:48px;">F</span>ILE HANDLING<span style="font-size:28px;"> [Try/Catch Statements]</span>
  </h1>
</div>

<div style="font-family:'Georgia', serif; font-size:18px; margin-top:10px; margin-left:50%;">
  – 27-02-2025 [Friday]
    <br>
    <br>
    <br>
</div>

In [55]:
import prime_1

print(prime_1.is_prime(10))

False


In [56]:
print("Hi")

Hi


###### <div style="font-family:'Georgia', serif; text-align:center;">
  <h1 style="font-size:36px; margin-bottom:0;">
    <span style="font-size:48px;">S</span>ESSION - 3 <span style="font-size:28px;">[On Numpy , Libraries , Pandas]</span>
  </h1>
</div>

<div style="font-family:'Georgia', serif; font-size:18px; margin-top:10px; margin-left:50%;">
  – 06-03-2026 [Friday]
    <br>
    <br>
    <br>
</div>

In [3]:
print("Hello World")

Hello World


In [4]:
import numpy
import pandas
import matplotlib.pyplot as plt
import scipy

x = [1,2,3,4]
y = [2,4,6,8]





ModuleNotFoundError: No module named 'scipy'

In [23]:
import numpy as np

x = 3.1415
y = np.float64(3.1415)

print(x)
print(y)
print(x == y)

3.1415
3.1415
True


In [24]:
x = np.int_(9232)
type(x)

numpy.int64

In [28]:
x = np.float64(3.1415)
type(x)

numpy.float64

In [39]:
a = np.ones([2,3])
print(a[1])


[1. 1. 1.]


In [43]:
import numpy as np
def is_stable():
    house = np.ones([3,3])

    for i in range(len(house)):
        for j in range(len(house[i])):
            if i + 1 < len(house):
                house[i][j] += 1
            if j + 1 < len(house[i]) :
                house[i][j] += 1
            if i - 1 > 0:
                house[i][j] += 1
            if j - 1 > 0:
                house[i][j] += 1
    print(house)

    print(house)




In [44]:
is_stable()

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [51]:
import numpy as np

def is_stable(A):
    for i in range(len(A)):
        for j in range(len(A[i])):
            neighbors = 0

            if i + 1 < len(A):
                neighbors += 1
            if j + 1 < len(A[i]):
                neighbors += 1
            if i - 1 >= 0:
                neighbors += 1
            if j - 1 >= 0:
                neighbors += 1

            if A[i][j] <= neighbors:
                return False
    return True

In [50]:
A = np.array([
    [5,4,3],
    [4,5,4],
    [3,4,3]
])

is_stable(A)

True

In [ ]:
x